message: ChangeResponseExampleMiddleware
trim: ChangeRequestExampleMiddleware
deny: RedirectExampleMiddleware
crsfToken: CsrfTokenMiddleware
requireLogin: RequireLoginMiddleware
previousPage: RememberPreviousPageMiddleware
grantAccess: GrantControllerAccessMiddleware
remember: RememberMeMiddleware
xss: XSSProtectionMiddleware
getUserCartFromCookie: GetUserCartFromCookieMiddleware
selectPaymentType: SelectPaymentTypeMiddleware
auth: AuthMiddleware
