message: ChangeResponseExampleMiddleware
trim: ChangeRequestExampleMiddleware
deny: RedirectExampleMiddleware
crsfToken: CsrfTokenMiddleware
requireLogin: RequireLoginMiddleware
return_to: RememberPreviousPageMiddleware
grantAccess: GrantAccessMiddleware
remember: RememberTokenCheckMiddleware
