/{title}/{id:\d+}/{page:\d+}:
  controller: products
  method: showPage
  httpMethod: post
  responseBody:
    type: RAW
    produces: text/xml
  ResponseStatus:
    HttpStatusCode: HTTP_OK
/product/{slug:[\w-]+}:
  controller: products
  method: show
"/home/index":
  controller: home
  method: index
"/products":
  controller: products
  method: index
"/":
  controller: home
  method: index

home:
  controller: home
  method: index
/_404_error:
  controller: errors
  method: index
/_500_error:
  controller: errors
  method: _500
admin:
  controller: admin_home
  method: index
/{controller}/new/{form:\d+}:
  method: new
/{controller}/show/{id:\d+}:
  method: show
  middleware: message|message
/{controller}/create:
  method: create
  middleware: trim
/{controller}/handleForm:
  method: handleForm
  middleware: trim
  httpMethod: post
/{controller}/edit/{id:\d+}:
  method: edit
/{controller}/update/{id:\d+}:
  method: update
/{controller}/delete/{id:\d+}:
  method: delete
/{controller}/destroy/{id:\d+}:
  method: destroy
  httpMethod: post
/admin/{controller}/{method}:
/{controller}/{method}:
  # /{controller}/{id:\d+}/{method}:
  # /{controller}/{method}/{id:\d+}:

