/{title}/{id:\d+}/{page:\d+}:
  controller: products
  method: showPage
  responseBody:
    type: RAW
    produces: text/xml
  ResponseStatus:
    HttpStatusCode: HTTP_OK
/product/{slug:[\w-]+}:
  controller: products
  method: show
/home/index:
  controller: home
  method: index
  httpMethod: get
  middleware: user
/products:
  controller: products
  method: index
  httpMethod: get
/:
  controller: home
  method: index
  httpMethod: get
/home:
  controller: home
  method: index
  httpMethod: get
/_404_error:
  controller: errors
  method: e_404
/_500_error:
  controller: errors
  method: e_500
/_client_error:
  controller: errors
  method: client-error
/_restrict:
  controller: errors
  method: restrict-access
/login:
  controller: login
  method: index
  httpMethod: get
  middleware: remember
/signup:
  controller: signup
  method: index
  httpMethod: get
/register:
  controller: signup
  method: register
  httpMethod: post
/auth-user:
  controller: login
  method: authenticate-user
  httpMethod: post
/user-from-cookie:
  controller: login-from-cookie
  method: index
  httpMethod: get
/logout:
  controller: logout
  method: index
  httpMethod: get
/forgot:
  controller: forgot-password
  method: index
  httpMethod: get
/password/reset/{token}:
  controller: forgot-password
  method: reset
  httpMethod: get
/signup/activate/{token}:
  controller: signup
  method: activate
  httpMethod: get
/reset-pw:
  controller: forgot-password
  method: reset-password
  httpMethod: post
/forgot-pw:
  controller: forgot-password
  method: process-forgot-password
  httpMethod: post
/save-profile:
  controller: profile
  method: update
/{controller}/index/{currentPage:\d+}:
  method: index
/_dev_error:
  controller: errors
  method: index
/{controller}/cms-show/{img:[\w-]+.(?:png|jpg)}:
  method: cms-show
/{controller}/new/{form:\d+}:
  method: new
/{controller}/show/{id:\d+}:
  method: show
/{controller}/{id:\d+}/show:
  method: show
/{controller}/create:
  method: create
  middleware: trim
  httpMethod: post
/{controller}/handleForm:
  method: handleForm
  middleware: trim
/{controller}/edit/{id:\d+}:
  method: edit
  middleware: requireLogin
/{controller}/{id:\d+}/edit:
  method: edit
  middleware: requireLogin
/{controller}/update/{id:\d+}:
  method: update
  middleware: requireLogin
/{controller}/{id:\d+}/update:
  method: update
  middleware: requireLogin
/{controller}/delete/{id:\d+}:
  method: delete
  middleware: requireLogin
/{controller}/{id:\d+}/delete:
  method: delete
  middleware: requireLogin
/{controller}/destroy/{id:\d+}:
  method: destroy
  httpMethod: post
  middleware: requireLogin
/admin/{controller}/{method}:
/{controller}/{method}:
  # /{controller}/{id:\d+}/{method}:
  # /{controller}/{method}/{id:\d+}:

