/{title}/{id:\d+}/{page:\d+}:
  controller: products
  method: showPage
/product/{slug:[\w-]+}:
  controller: products
  method: show
"/home/index":
  controller: home
  method: index
"/products":
  controller: products
  method: index
"/":
  controller: home
  method: index
home:
  controller: home
  method: index
/_404_error:
  controller: errors
  method: index
/_500_error:
  controller: errors
  method: _500
admin:
  controller: admin_home
  method: index
# /{controller}/show/{id:\d+}:
#   method: show
# /{controller}/edit/{id:\d+}:
#   method: edit
# /{controller}/update/{id:\d+}:
#   method: update
# /{controller}/delete/{id:\d+}:
#   method: delete
# /{controller}/destroy/{id:\d+}:
#   method: destroy
#   httpMethod: post
/admin/{controller}/{method}:
/{controller}/{id:\d+}/{method}:
/{controller}/{method}/{id:\d+}:
/{controller}/{method}:
